version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    volumes:
      - weather_stats_db_data:/var/lib/postgresql/data

  # app:
  #   build: . # Builds from the Dockerfile in the current directory
  #   ports:
  #     - "5000:5000" # Example for a web application
  #   environment:
  #     DATABASE_URL: postgresql://your_username:your_password@db:5432/your_database_name
  #   depends_on:
  #     - db

volumes:
  weather_stats_db_data: